### ISSUE TITLE
Autoformat on save giving error about a file

### ISSUE THREAD

**Issue by renovatorruler** [AestheticIntegration/iml-vscode#2]
I think there is a hard-coded address somewhere:

``[Error - 11:41:56 AM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: ENOENT: no such file or directory, open '/Users/ewenmaclean/testout.txt'
  Code: -32603``

OS: Fedora 29
VS Code Version: 1.31.1
iml-vscode: 0.2.4

Steps to reproduce:
Enable 'Format on Save' setting in the editor.
Open an iml file, try to save it.
Watch the output pane.

**Comment by ewenmaclean** [comment]
@prashantpawar many thanks indeed for pointing this out. I have now fixed this on release 0.2.7 of the imandra IDE - my apologies for this.

**Comment by ignaden** [comment]
Resolved in 0.2.7
